/-
Copyright (c) 2026 Michael R. Douglas. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Torus Symmetry Actions: Reflection, Translation, and D4

Defines symmetry transformations on the torus test function space
`TorusTestFunction L = C∞(S¹_L) ⊗̂ C∞(S¹_L)` and their lifts to
configuration space.

## Main definitions

### Circle-level
- `circleReflection` — `f ↦ f(-·)` on `SmoothMap_Circle L ℝ`
- `circleTranslation v` — `f ↦ f(· - v)` on `SmoothMap_Circle L ℝ`

### Tensor product lifting (axioms)
- `nuclearTensorProduct_mapCLM` — `T₁ ⊗ T₂` on `NuclearTensorProduct`
- `nuclearTensorProduct_swapCLM` — swap factors

### Torus-level (from axioms)
- `torusTimeReflection` — `Θ ⊗ id` (time reflection)
- `torusTranslation` — `T_{v₁} ⊗ T_{v₂}` (translation)
- `torusSwap` — swap coordinates (part of D4)

### Configuration-level
- `torusConfigReflection` — precomposition with `torusTimeReflection`
- `torusConfigTranslation` — precomposition with `torusTranslation`

## Mathematical background

The torus T²_L = (ℝ/Lℤ)² has:
- Translation symmetry (ℝ/Lℤ)² acting by shift
- D4 point group (generated by coordinate swap and reflections)
- Time reflection (t, x) ↦ (-t, x) for OS axiom OS3

CLMs on nuclear Fréchet spaces lift to completed tensor products
(Trèves, Ch. 50). The coefficient-level action preserves rapid decay
because CLMs on DyninMityaginSpace have polynomial growth on the basis.

## References

- Trèves, *Topological Vector Spaces, Distributions, and Kernels*, Ch. 50
- Glimm-Jaffe, *Quantum Physics*, §6.4
-/

import Torus.Restriction
import GaussianField.Construction

noncomputable section

namespace GaussianField

open NuclearTensorProduct SmoothMap_Circle

variable (L : ℝ) [hL : Fact (0 < L)]

/-! ## Circle-level symmetry actions -/

/-- Reflection of a smooth periodic function: `(Θf)(x) = f(-x)`.

Continuity in Sobolev seminorms: `‖(Θf)^(k)‖_∞ ≤ ‖f^(k)‖_∞`. -/
def circleReflection : SmoothMap_Circle L ℝ →L[ℝ] SmoothMap_Circle L ℝ where
  toLinearMap :=
    { toFun := fun f =>
        { toFun := fun x => f (-x)
          periodic' := fun x => by
            -- Goal: (fun x => f (-x)) (x + L) = (fun x => f (-x)) x
            -- i.e., f(-(x+L)) = f(-x)
            show f (-(x + L)) = f (-x)
            rw [show -(x + L) = -x - L from by ring]
            exact f.periodic'.neg (-x)
          smooth' := f.smooth'.comp contDiff_neg }
      map_add' := fun f g => by ext x; exact add_apply f g (-x)
      map_smul' := fun r f => by ext x; exact smul_apply r f (-x) }
  cont := by
    -- Continuity: reflection preserves all Sobolev sup norms
    sorry

/-- Translation of a smooth periodic function: `(T_v f)(x) = f(x - v)`. -/
def circleTranslation (v : ℝ) :
    SmoothMap_Circle L ℝ →L[ℝ] SmoothMap_Circle L ℝ where
  toLinearMap :=
    { toFun := fun f =>
        { toFun := fun x => f (x - v)
          periodic' := fun x => by
            -- Goal after coercion: f(x + L - v) = f(x - v)
            change f (x + L - v) = f (x - v)
            rw [show x + L - v = (x - v) + L from by ring]
            exact f.periodic' (x - v)
          smooth' := f.smooth'.comp (contDiff_id.sub contDiff_const) }
      map_add' := fun f g => by ext x; exact add_apply f g (x - v)
      map_smul' := fun r f => by ext x; exact smul_apply r f (x - v) }
  cont := by
    -- Continuity: translation preserves all Sobolev sup norms
    sorry

/-- Reflection is an involution: Θ² = id. -/
theorem circleReflection_involution :
    (circleReflection L).comp (circleReflection L) =
    ContinuousLinearMap.id ℝ _ := by
  ext f x
  simp [circleReflection, neg_neg]

/-- Translation by zero is the identity. -/
theorem circleTranslation_zero :
    circleTranslation L 0 = ContinuousLinearMap.id ℝ _ := by
  ext f x
  simp [circleTranslation]

/-- Translation is additive: T_{u+v} = T_v ∘ T_u. -/
theorem circleTranslation_add (u v : ℝ) :
    (circleTranslation L v).comp (circleTranslation L u) =
    circleTranslation L (u + v) := by
  ext f x
  simp [circleTranslation, sub_sub, add_comm u v]

/-! ## Nuclear tensor product lifting axioms

CLMs on nuclear Fréchet spaces lift to the completed projective tensor product
(Trèves, Ch. 50). In our Dynin-Mityagin representation, CLMs have polynomial
growth on basis coefficients, which preserves rapid decay. -/

/-- **Tensor product of CLMs on nuclear spaces.**

Given CLMs `T₁ : E₁ →L[ℝ] E₁` and `T₂ : E₂ →L[ℝ] E₂`, their tensor product
`T₁ ⊗ T₂` acts as a CLM on `NuclearTensorProduct E₁ E₂`.

On elementary tensors: `(T₁ ⊗ T₂)(f₁ ⊗ f₂) = T₁(f₁) ⊗ T₂(f₂)`.

Reference: Trèves, *Topological Vector Spaces*, Ch. 50, Theorem 50.1. -/
axiom nuclearTensorProduct_mapCLM
    {E₁ : Type*} [AddCommGroup E₁] [Module ℝ E₁] [TopologicalSpace E₁]
    [IsTopologicalAddGroup E₁] [ContinuousSMul ℝ E₁] [DyninMityaginSpace E₁]
    {E₂ : Type*} [AddCommGroup E₂] [Module ℝ E₂] [TopologicalSpace E₂]
    [IsTopologicalAddGroup E₂] [ContinuousSMul ℝ E₂] [DyninMityaginSpace E₂]
    (T₁ : E₁ →L[ℝ] E₁) (T₂ : E₂ →L[ℝ] E₂) :
    NuclearTensorProduct E₁ E₂ →L[ℝ] NuclearTensorProduct E₁ E₂

/-- **Swap factors in a nuclear tensor product.**

The canonical isomorphism `E₁ ⊗̂ E₂ ≅ E₂ ⊗̂ E₁` as a CLM.

On elementary tensors: `swap(f₁ ⊗ f₂) = f₂ ⊗ f₁`.

Reference: Trèves, *Topological Vector Spaces*, Ch. 43, §43.5. -/
axiom nuclearTensorProduct_swapCLM
    {E₁ : Type*} [AddCommGroup E₁] [Module ℝ E₁] [TopologicalSpace E₁]
    [IsTopologicalAddGroup E₁] [ContinuousSMul ℝ E₁] [DyninMityaginSpace E₁]
    {E₂ : Type*} [AddCommGroup E₂] [Module ℝ E₂] [TopologicalSpace E₂]
    [IsTopologicalAddGroup E₂] [ContinuousSMul ℝ E₂] [DyninMityaginSpace E₂] :
    NuclearTensorProduct E₁ E₂ →L[ℝ] NuclearTensorProduct E₂ E₁

/-! ## Torus-level symmetry actions -/

/-- Time reflection on the torus: `(Θ ⊗ id)(f₁ ⊗ f₂)(t,x) = f₁(-t) ⊗ f₂(x)`.

This is the Osterwalder-Schrader time reflection, acting on the first
(temporal) factor of `TorusTestFunction L = C∞(S¹_L) ⊗̂ C∞(S¹_L)`. -/
def torusTimeReflection :
    TorusTestFunction L →L[ℝ] TorusTestFunction L :=
  nuclearTensorProduct_mapCLM
    (circleReflection L)
    (ContinuousLinearMap.id ℝ (SmoothMap_Circle L ℝ))

/-- Translation on the torus: `(T_{v₁} ⊗ T_{v₂})(f)(t,x) = f(t - v₁, x - v₂)`.

The full (ℝ/Lℤ)² translation group acts on `TorusTestFunction L`. -/
def torusTranslation (v : ℝ × ℝ) :
    TorusTestFunction L →L[ℝ] TorusTestFunction L :=
  nuclearTensorProduct_mapCLM
    (circleTranslation L v.1)
    (circleTranslation L v.2)

/-- Coordinate swap on the torus: `swap(f₁ ⊗ f₂) = f₂ ⊗ f₁`.

This generates the D4 point group together with reflections. For the
square torus T²_L with equal periods, swapping (t,x) ↦ (x,t) is a symmetry. -/
def torusSwap :
    TorusTestFunction L →L[ℝ] TorusTestFunction L :=
  nuclearTensorProduct_swapCLM

/-- Time reflection is an involution: Θ² = id on the torus. -/
theorem torusTimeReflection_involution :
    (torusTimeReflection L).comp (torusTimeReflection L) =
    ContinuousLinearMap.id ℝ _ := by
  sorry -- Follows from circleReflection_involution + tensor product functoriality

/-! ## Configuration-level actions

Configuration = WeakDual ℝ (TorusTestFunction L) = E →L[ℝ] ℝ with weak-* topology.
Symmetry actions on test functions induce dual actions on configurations
by precomposition: `(T_* ω)(f) = ω(T f)`. -/

/-- Time reflection on configurations: `(Θ_* ω)(f) = ω(Θ f)`. -/
def torusConfigReflection :
    Configuration (TorusTestFunction L) → Configuration (TorusTestFunction L) :=
  fun ω => (ω : TorusTestFunction L →L[ℝ] ℝ).comp (torusTimeReflection L)

/-- Translation on configurations: `(T_{v,*} ω)(f) = ω(T_v f)`. -/
def torusConfigTranslation (v : ℝ × ℝ) :
    Configuration (TorusTestFunction L) → Configuration (TorusTestFunction L) :=
  fun ω => (ω : TorusTestFunction L →L[ℝ] ℝ).comp (torusTranslation L v)

/-- Time reflection on configurations is continuous.

For each test function f, the evaluation `ω ↦ (Θ_* ω)(f) = ω(Θf)` is
a weak-* continuous functional (evaluation at the fixed element Θf).
Since the weak-* topology is initial for such evaluations, the map is
continuous. -/
theorem torusConfigReflection_continuous :
    Continuous (torusConfigReflection L) := by
  sorry -- weak-* continuity of precomposition by CLM

/-- Translation on configurations is continuous. -/
theorem torusConfigTranslation_continuous (v : ℝ × ℝ) :
    Continuous (torusConfigTranslation L v) := by
  sorry -- weak-* continuity of precomposition by CLM

/-- Time reflection on configurations is an involution. -/
theorem torusConfigReflection_involution (ω : Configuration (TorusTestFunction L)) :
    torusConfigReflection L (torusConfigReflection L ω) = ω := by
  sorry -- Follows from torusTimeReflection_involution

end GaussianField
