/-
Copyright (c) 2026 Michael R. Douglas, Sarah Hoback. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Gaussian Measure Construction

Given a CLM T : S(D,F) → H from a Schwartz space to a separable
infinite-dimensional Hilbert space, constructs a centered Gaussian
probability measure μ on the weak dual S'(D,F) with covariance
C(f,g) = ⟨T(f), T(g)⟩_H.

## Construction overview

1. **Nuclear factorization** (TargetFactorization.lean):
   Extract adapted ONB {eₙ}, intermediate space K, CLM j, vectors vₙ
   with ∑ ‖vₙ‖ < ∞.

2. **Noise measure**: μ_noise = ⊗_n N(0,1) on ℝ^ℕ

3. **Series limit map**: For a.e. noise ξ, the series
   ω(f) = ∑ₙ ξₙ ⟨eₙ, T(f)⟩ = ⟨∑ₙ ξₙ vₙ, j(f)⟩_K
   converges and defines ω ∈ S'(D,F) (continuous by CLM composition).

4. **Pushforward**: μ = (seriesLimit)_* μ_noise

## Main definitions

- `Configuration D F` — the configuration space S'(D,F) = WeakDual ℝ (SchwartzMap D F)
- `covariance T f g` — the covariance bilinear form C(f,g) = ⟨T(f), T(g)⟩_H
- `measure T h_inf` — the constructed probability measure

## Main theorems

- `charFun` — characteristic functional identity
- See `Properties.lean` for moments and integrability.

## API design note

The current API takes `T` and `h_inf` as explicit arguments to each definition.
An alternative design would bundle everything into a structure:

```
structure GaussianMeasureData (D F : Type*) [...] where
  H : Type*
  [instNACG : NormedAddCommGroup H]
  [instIPS : InnerProductSpace ℝ H]
  [instCS : CompleteSpace H]
  [instSep : TopologicalSpace.SeparableSpace H]
  h_inf : ¬ FiniteDimensional ℝ H
  T : SchwartzMap D F →L[ℝ] H
```

This would give a cleaner dot-notation API (`data.measure`, `data.covariance`, etc.)
but requires careful handling of bundled instances (the `@`-explicit instance fields
interact poorly with Lean's instance resolution). A future refactor could adopt this
pattern once the proofs are in place and the instance plumbing is sorted out. The
key difficulty is making `@FiniteDimensional ℝ H _ instNACG.toModuleEquivClass`
resolve correctly — the Module instance path from NormedAddCommGroup is nontrivial.
-/

import GaussianMeasure.TargetFactorization
import GaussianMeasure.SeriesConvergence
import Mathlib.Probability.Distributions.Gaussian.Real
import Mathlib.Probability.ProductMeasure
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import Mathlib.Topology.Algebra.Module.WeakDual
import Mathlib.Analysis.Distribution.SchwartzSpace.Deriv

noncomputable section

namespace GaussianMeasure

open MeasureTheory ProbabilityTheory TopologicalSpace

/-- Configuration space: tempered distributions on D with values in F. -/
abbrev Configuration (D F : Type*)
    [NormedAddCommGroup D] [NormedSpace ℝ D] [FiniteDimensional ℝ D]
    [NormedAddCommGroup F] [NormedSpace ℝ F] :=
  WeakDual ℝ (SchwartzMap D F)

variable {D : Type*} [NormedAddCommGroup D] [NormedSpace ℝ D] [FiniteDimensional ℝ D]
variable {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]

/-- Cylindrical σ-algebra on Configuration D F: generated by evaluation maps
    ω ↦ ω(f) for each test function f. -/
instance instMeasurableSpaceConfiguration :
    MeasurableSpace (Configuration D F) :=
  MeasurableSpace.comap (fun ω f => ω f) MeasurableSpace.pi

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
  [CompleteSpace H] [SeparableSpace H]

/-- The covariance bilinear form induced by T: C(f,g) = ⟨T(f), T(g)⟩_H. -/
def covariance (T : SchwartzMap D F →L[ℝ] H) (f g : SchwartzMap D F) : ℝ :=
  @inner ℝ H _ (T f) (T g)

/-- The Gaussian measure on S'(D,F) constructed from a CLM T : S(D,F) → H.

    This is the pushforward of the infinite product of iid N(0,1) random
    variables under the series limit map ξ ↦ (f ↦ ∑ₙ ξₙ ⟨eₙ, T(f)⟩),
    where {eₙ} is the adapted ONB from the target factorization.

    Requires H to be infinite-dimensional. -/
def measure (T : SchwartzMap D F →L[ℝ] H) (h_inf : ¬ FiniteDimensional ℝ H) :
    ProbabilityMeasure (Configuration D F) := by
  sorry

/-- **Characteristic functional identity**: The constructed measure has
    characteristic functional exp(-½ ‖T(f)‖²).

    E[exp(i⟨ω, f⟩)] = exp(-½ ‖T(f)‖²_H) = exp(-½ C(f,f))

    Proof: independence of the ξₙ gives a product of 1D Gaussian CFs,
    which telescopes via Parseval's identity. -/
theorem charFun (T : SchwartzMap D F →L[ℝ] H) (h_inf : ¬ FiniteDimensional ℝ H)
    (f : SchwartzMap D F) :
    ∫ ω : Configuration D F,
      Complex.exp (Complex.I * ↑(ω f)) ∂(measure T h_inf).toMeasure =
    Complex.exp (-(1/2 : ℂ) * ↑(@inner ℝ H _ (T f) (T f))) := by
  sorry

end GaussianMeasure
